name: ${name}
version: ${version}
main: ${groupId}.essentials.ZAPEssentialsPlugin
api-version: 1.16
depend: [ arena-api ]
commands:
  serializestack:
    description: Serializes the item in your hand.
  lemmesee:
    permission: io.github.zap.lemmesee
